// The one fetch wrapper, the queries everyone shares, and small formatters.
// Response types come from src/api/types (generated by ts-rs from the Rust
// structs, ADR 0007) — never hand-write one here.

import { useQuery } from '@tanstack/react-query'
import type { Me } from './api/types/Me'
import type { AgentsResponse } from './api/types/AgentsResponse'
import type { CategoriesResponse } from './api/types/CategoriesResponse'
import type { Ticket } from './api/types/Ticket'

export class ApiError extends Error {
  status: number
  code: string
  constructor(status: number, code: string) {
    super(code)
    this.status = status
    this.code = code
  }
}

export const errorCode = (e: unknown) => (e instanceof ApiError ? e.code : e ? 'network' : null)

async function request<T>(method: string, path: string, body?: unknown): Promise<T> {
  // Every mutating request carries Content-Type: application/json, even
  // without a body: that header is the CSRF defence (ADR 0006).
  const res = await fetch('/api' + path, {
    method,
    credentials: 'same-origin',
    headers: method === 'GET' ? undefined : { 'Content-Type': 'application/json' },
    body: method === 'GET' ? undefined : JSON.stringify(body ?? {}),
  })
  if (res.status === 204) return undefined as T
  const data = await res.json().catch(() => ({}))
  if (!res.ok) throw new ApiError(res.status, data.error ?? `http${res.status}`)
  return data as T
}

export const api = {
  get: <T>(path: string) => request<T>('GET', path),
  post: <T = void>(path: string, body?: unknown) => request<T>('POST', path, body),
  patch: <T>(path: string, body: unknown) => request<T>('PATCH', path, body),
  put: <T>(path: string, body: unknown) => request<T>('PUT', path, body),
  del: (path: string) => request<void>('DELETE', path),
}

export const useMe = (refetchInterval?: number) =>
  useQuery({ queryKey: ['me'], queryFn: () => api.get<Me>('/me'), refetchInterval })

export const useAgents = () =>
  useQuery({ queryKey: ['agents'], queryFn: () => api.get<AgentsResponse>('/agents') })

export const useCategories = () =>
  useQuery({ queryKey: ['categories'], queryFn: () => api.get<CategoriesResponse>('/categories') })

export const STATUS_LABELS: Record<Ticket['status'], string> = {
  new: 'New',
  waitingOnContact: 'Waiting on contact',
  waitingOnUs: 'Waiting on us',
  closed: 'Closed',
}

export const PRIORITY_LABELS: Record<NonNullable<Ticket['priority']>, string> = {
  low: 'Low',
  medium: 'Medium',
  high: 'High',
  urgent: 'Urgent',
}

// Shown where the beta sends people to us (spec 001 open question 1).
export const BETA_CONTACT = 'hello@muninn.io'

export const pct = (p: number) => `${Math.round(p * 100)}%`

export const formatDate = (iso: string) =>
  new Date(iso).toLocaleString(undefined, { dateStyle: 'medium', timeStyle: 'short' })

const rtf = new Intl.RelativeTimeFormat(undefined, { numeric: 'auto' })

export function ago(iso: string) {
  const s = (new Date(iso).getTime() - Date.now()) / 1000
  const abs = Math.abs(s)
  if (abs < 60) return 'just now'
  if (abs < 3600) return rtf.format(Math.round(s / 60), 'minute')
  if (abs < 86400) return rtf.format(Math.round(s / 3600), 'hour')
  if (abs < 86400 * 30) return rtf.format(Math.round(s / 86400), 'day')
  return new Date(iso).toLocaleDateString()
}

export const formatSize = (n: number) =>
  n < 1024 ? `${n} B` : n < 1024 * 1024 ? `${Math.round(n / 1024)} KB` : `${(n / 1024 / 1024).toFixed(1)} MB`
