// The one fetch wrapper, the queries everyone shares, and small formatters.
// Response types come from src/api/types (generated by ts-rs from the Rust
// structs, ADR 0007) — never hand-write one here.

import { useEffect, useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import type { Me } from './api/types/Me'
import type { AgentsResponse } from './api/types/AgentsResponse'
import type { CategoriesResponse } from './api/types/CategoriesResponse'
import type { SnippetsResponse } from './api/types/SnippetsResponse'
import type { Ticket } from './api/types/Ticket'
import type { ViewFilters } from './api/types/ViewFilters'
import type { ViewsResponse } from './api/types/ViewsResponse'
import type { HubspotStatus } from './api/types/HubspotStatus'

export class ApiError extends Error {
  status: number
  code: string
  constructor(status: number, code: string) {
    super(code)
    this.status = status
    this.code = code
  }
}

export const errorCode = (e: unknown) => (e instanceof ApiError ? e.code : e ? 'network' : null)

async function request<T>(method: string, path: string, body?: unknown): Promise<T> {
  // Every mutating request carries Content-Type: application/json, even
  // without a body: that header is the CSRF defence (ADR 0006).
  const res = await fetch('/api' + path, {
    method,
    credentials: 'same-origin',
    headers: method === 'GET' ? undefined : { 'Content-Type': 'application/json' },
    body: method === 'GET' ? undefined : JSON.stringify(body ?? {}),
  })
  if (res.status === 204) return undefined as T
  const data = await res.json().catch(() => ({}))
  if (!res.ok) throw new ApiError(res.status, data.error ?? `http${res.status}`)
  return data as T
}

export const api = {
  get: <T>(path: string) => request<T>('GET', path),
  post: <T = void>(path: string, body?: unknown) => request<T>('POST', path, body),
  patch: <T>(path: string, body: unknown) => request<T>('PATCH', path, body),
  put: <T>(path: string, body: unknown) => request<T>('PUT', path, body),
  del: (path: string) => request<void>('DELETE', path),
}

export const useMe = (refetchInterval?: number) =>
  useQuery({ queryKey: ['me'], queryFn: () => api.get<Me>('/me'), refetchInterval })

export const useAgents = () =>
  useQuery({ queryKey: ['agents'], queryFn: () => api.get<AgentsResponse>('/agents') })

export const useCategories = () =>
  useQuery({ queryKey: ['categories'], queryFn: () => api.get<CategoriesResponse>('/categories') })

export const useViews = () => useQuery({ queryKey: ['views'], queryFn: () => api.get<ViewsResponse>('/views') })

export const useSnippets = () =>
  useQuery({ queryKey: ['snippets'], queryFn: () => api.get<SnippetsResponse>('/snippets') })

// Spec 006: the list's filters, as GET /api/tickets and the URL both take them.
export const BUILTIN_VIEWS = ['unassigned', 'mine', 'open', 'snoozed', 'drafts', 'closed', 'all'] as const
export const isBuiltin = (v: string): v is ViewFilters['view'] => (BUILTIN_VIEWS as readonly string[]).includes(v)

export const VIEW_LABELS: Record<ViewFilters['view'], string> = {
  unassigned: 'Unassigned',
  mine: 'Assigned to me',
  open: 'All open',
  snoozed: 'Snoozed',
  drafts: 'Drafts',
  closed: 'Closed',
  all: 'All tickets',
}

export const SORT_LABELS: Record<ViewFilters['sort'], string> = {
  recent: 'Last activity',
  oldest: 'Oldest activity',
  waiting: 'Waiting longest',
  priority: 'Priority',
  created: 'Created',
}

export const CREATED_LABELS: Record<NonNullable<ViewFilters['created']>, string> = {
  '24h': 'Last 24 hours',
  '7d': 'Last 7 days',
  '30d': 'Last 30 days',
}

export function ticketsQuery(f: ViewFilters) {
  const p = new URLSearchParams({ view: f.view })
  if (f.q) p.set('q', f.q)
  for (const k of ['status', 'owner', 'priority', 'category'] as const) if (f[k].length) p.set(k, f[k].join(','))
  if (f.created) p.set('created', f.created)
  if (f.unread) p.set('unread', 'true')
  if (f.seenBefore) p.set('seenBefore', 'true')
  if (f.sort !== 'recent') p.set('sort', f.sort)
  return p.toString()
}

export const sameFilters = (a: ViewFilters, b: ViewFilters) => ticketsQuery(a) === ticketsQuery(b)

// §43: one clock for every relative time, ticking each minute.
let now = Date.now()
const ticks = new Set<(n: number) => void>()
setInterval(() => {
  now = Date.now()
  ticks.forEach((f) => f(now))
}, 60_000)
export function useNow() {
  const [n, setN] = useState(now)
  useEffect(() => {
    ticks.add(setN)
    return () => void ticks.delete(setN)
  }, [])
  return n
}

// "Waiting 3 h" (§16), in whole units.
export function duration(fromIso: string, to = Date.now()) {
  const m = Math.max(0, Math.floor((to - new Date(fromIso).getTime()) / 60_000))
  if (m < 60) return `${m} min`
  if (m < 60 * 24) return `${Math.floor(m / 60)} h`
  return `${Math.floor(m / 60 / 24)} d`
}

// "Mon 09:00", with the date when it is more than six days away (§25).
export function formatSnooze(iso: string) {
  const d = new Date(iso)
  const far = d.getTime() - Date.now() > 6 * 86_400_000
  return d.toLocaleString(undefined, {
    weekday: 'short',
    ...(far ? { day: 'numeric', month: 'short' } : {}),
    hour: '2-digit',
    minute: '2-digit',
  })
}

// §25: in the agent's local time.
export function snoozeTimes(from = new Date()) {
  const tomorrow = new Date(from)
  tomorrow.setDate(from.getDate() + 1)
  tomorrow.setHours(9, 0, 0, 0)
  const monday = new Date(from)
  monday.setDate(from.getDate() + ((8 - from.getDay()) % 7 || 7))
  monday.setHours(9, 0, 0, 0)
  return [
    { label: 'Later today', at: new Date(from.getTime() + 3 * 3_600_000) },
    { label: 'Tomorrow', at: tomorrow },
    { label: 'Next week', at: monday },
  ]
}

// §41: stored on this device. Storage can be unavailable (private mode, blocked).
const SHORTCUTS_KEY = 'muninn.shortcuts'
export function shortcutsOn() {
  try {
    return localStorage.getItem(SHORTCUTS_KEY) !== 'off'
  } catch {
    return true
  }
}
export function setShortcutsOn(on: boolean) {
  try {
    localStorage.setItem(SHORTCUTS_KEY, on ? 'on' : 'off')
  } catch {
    // Not stored: the setting lasts until reload.
  }
}

// §44: the same colour for a person everywhere, from their email.
export function avatarColor(key: string) {
  let h = 0
  for (const ch of key.toLowerCase()) h = (h * 31 + ch.charCodeAt(0)) % 360
  return `hsl(${h}, 45%, 42%)`
}
export const initials = (name: string) =>
  name
    .split(/[\s@.]+/)
    .filter(Boolean)
    .slice(0, 2)
    .map((w) => w[0]!.toUpperCase())
    .join('')
// Spec 007: null when the server has no HubSpot app (404), so callers hide
// HubSpot altogether. Polls while an import runs.
export const useHubspot = () =>
  useQuery({
    queryKey: ['hubspot'],
    queryFn: () =>
      api.get<HubspotStatus>('/integrations/hubspot').catch((e) => {
        if (e instanceof ApiError && e.status === 404) return null
        throw e
      }),
    refetchInterval: (q) => (q.state.data?.connection?.status === 'importing' ? 3000 : false),
  })

export const STATUS_LABELS: Record<Ticket['status'], string> = {
  new: 'New',
  waitingOnContact: 'Waiting on contact',
  waitingOnUs: 'Waiting on us',
  closed: 'Closed',
}

export const PRIORITY_LABELS: Record<NonNullable<Ticket['priority']>, string> = {
  low: 'Low',
  medium: 'Medium',
  high: 'High',
  urgent: 'Urgent',
}

// Shown where the beta sends people to us (spec 001 open question 1).
export const BETA_CONTACT = 'hello@muninn.io'

export const pct = (p: number) => `${Math.round(p * 100)}%`

export const formatDate = (iso: string) =>
  new Date(iso).toLocaleString(undefined, { dateStyle: 'medium', timeStyle: 'short' })

const rtf = new Intl.RelativeTimeFormat(undefined, { numeric: 'auto' })

export function ago(iso: string) {
  const s = (new Date(iso).getTime() - Date.now()) / 1000
  const abs = Math.abs(s)
  if (abs < 60) return 'just now'
  if (abs < 3600) return rtf.format(Math.round(s / 60), 'minute')
  if (abs < 86400) return rtf.format(Math.round(s / 3600), 'hour')
  if (abs < 86400 * 30) return rtf.format(Math.round(s / 86400), 'day')
  return new Date(iso).toLocaleDateString()
}

export const formatSize = (n: number) =>
  n < 1024 ? `${n} B` : n < 1024 * 1024 ? `${Math.round(n / 1024)} KB` : `${(n / 1024 / 1024).toFixed(1)} MB`
