// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Agent } from "./Agent";
import type { Invite } from "./Invite";

export type AgentsResponse = { agents: Array<Agent>, invites: Array<Invite>, };
