// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AttachmentMeta = { id: string, name: string, contentType: string, size: number, };
