// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Totp } from "./Totp";

/**
 * `GET /api/auth/link` — what the `/auth` page shows before it is submitted.
 */
export type AuthLinkInfo = { purpose: 'invite' | 'setup' | 'reset', workspaceName: string, email: string, 
/**
 * The authenticator to set up; null on `reset`, which uses the existing one.
 */
totp: Totp | null, };
