// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `GET /api/auth/link` — what the `/auth` page shows before the button.
 */
export type AuthLinkInfo = { purpose: 'signup' | 'login' | 'invite', workspaceName: string, email: string, 
/**
 * Signup only, so "slug taken" can send the visitor back with the form filled.
 */
slug: string | null, language: string | null, };
