// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Billing = { status: 'trialing' | 'trialExpired' | 'active' | 'pastDue' | 'canceled', trialEndsAt: string, locked: boolean, };
