// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ContactTicket = { id: string, subject: string, status: 'new' | 'waitingOnContact' | 'waitingOnUs' | 'closed', createdAt: string, };
