// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Counts = { unassigned: number, mine: number, open: number, drafts: number, 
/**
 * Every saved view the agent can see, by id.
 */
views: { [key in string]: number }, };
