// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `PUT /api/tickets/{id}/draft` — empty text deletes it.
 */
export type DraftRequest = { mode: 'reply' | 'comment', text: string, };
