// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HubspotPipeline } from "./HubspotPipeline";
import type { ImportProgress } from "./ImportProgress";

export type HubspotConnection = { accountId: number, accountName: string, status: 'pickPipelines' | 'importing' | 'synced' | 'revoked', pipelines: Array<HubspotPipeline>, 
/**
 * Set while `importing`, otherwise null.
 */
import: ImportProgress | null, tickets: number, skipped: number, lastSyncedAt: string | null, lastError: string | null, connectedAt: string, };
