// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ImportProgress = { done: number, 
/**
 * HubSpot's own count; it can move while the import runs.
 */
total: number, };
