// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LastMessage = { kind: 'customer' | 'agent' | 'comment', snippet: string, at: string, };
