// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `lastMessage`, and `searchMatch` (spec 006 §13).
 */
export type LastMessage = { kind: 'customer' | 'agent' | 'comment', 
/**
 * The display name of whoever wrote it.
 */
author: string, snippet: string, at: string, };
