// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `POST /api/login` and `POST /api/auth/link`: where the SPA goes next.
 */
export type LoginResponse = { redirect: string, };
