// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AttachmentMeta } from "./AttachmentMeta";
import type { Author } from "./Author";
import type { Delivery } from "./Delivery";

export type Message = { id: string, kind: 'customer' | 'agent' | 'comment', author: Author, text: string, at: string, 
/**
 * Null except on `agent`.
 */
delivery: Delivery | null, attachments: Array<AttachmentMeta>, };
