// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PatchTicketsItem } from "./PatchTicketsItem";

/**
 * `PATCH /api/tickets` — several at once, all or nothing (spec 006 §23).
 */
export type PatchTickets = { tickets: Array<PatchTicketsItem>, };
