// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PatchTicketsItem = { id: string, status?: 'new' | 'waitingOnContact' | 'waitingOnUs' | 'closed', ownerId?: string | null, priority?: 'low' | 'medium' | 'high' | 'urgent' | null, categoryId?: string | null, 
/**
 * `null` unsnoozes (spec 006 §25–27).
 */
snoozedUntil?: string | null, };
