// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ViewFilters } from "./ViewFilters";

export type PatchView = { name?: string, shared?: boolean, filters?: ViewFilters, };
