// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `POST /api/tickets/{id}/replies`.
 */
export type ReplyRequest = { text: string, 
/**
 * The ticket's status after the reply (spec 006 §33).
 */
status?: 'waitingOnContact' | 'closed', 
/**
 * The newest message the agent has seen; omitted, nothing is checked (§36).
 */
after?: string, };
