// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DnsRecord } from "./DnsRecord";

export type SendingDomain = { fromAddress: string | null, status: 'pending' | 'verified' | null, dnsRecords: Array<DnsRecord>, };
