// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NameOnly } from "./NameOnly";

export type Solution = { text: string, author: NameOnly, at: string, };
