// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Case } from "./Case";
import type { Solution } from "./Solution";

export type Suggestion = { id: string, case: Case, score: number, 
/**
 * Null for a case closed without an agent reply.
 */
solution: Solution | null, myFeedback: 'helped' | 'notRelevant' | null, };
