// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Suggestion } from "./Suggestion";

/**
 * `GET /api/tickets/{id}/suggestions`
 */
export type Suggestions = { status: 'pending' | 'ready' | 'failed', brainSize: number, suggestions: Array<Suggestion>, };
