// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Reply and internal comment bodies.
 */
export type TextRequest = { text: string, };
