// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Ticket } from "./Ticket";

/**
 * `PATCH /api/tickets`, in request order.
 */
export type TicketsResponse = { tickets: Array<Ticket>, };
