// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TicketCategory = { id: string, name: string, source: 'jev' | 'agent', 
/**
 * Jev's when `source` is `jev`, otherwise null.
 */
probability: number | null, };
