// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Counts } from "./Counts";
import type { Ticket } from "./Ticket";

/**
 * `GET /api/tickets?view=…`
 */
export type TicketList = { tickets: Array<Ticket>, nextCursor: string | null, counts: Counts, 
/**
 * False until the workspace's first mail: the SPA shows forwarding
 * instructions instead of an empty view (spec 002 §13).
 */
hasTickets: boolean, };
