// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentRef } from "./AgentRef";
import type { CategorySuggestion } from "./CategorySuggestion";
import type { Contact } from "./Contact";
import type { ContactTicket } from "./ContactTicket";
import type { LastMessage } from "./LastMessage";
import type { Message } from "./Message";
import type { TicketCategory } from "./TicketCategory";

/**
 * `GET /api/tickets/{id}` — the Ticket plus its thread.
 */
export type TicketDetail = { messages: Array<Message>, contactTickets: Array<ContactTicket>, id: string, subject: string, status: 'new' | 'waitingOnContact' | 'waitingOnUs' | 'closed', priority: 'low' | 'medium' | 'high' | 'urgent' | null, owner: AgentRef | null, contact: Contact, category: TicketCategory | null, categorySuggestions: Array<CategorySuggestion>, seenBefore: boolean, lastMessage: LastMessage, createdAt: string, lastActivityAt: string, };
