// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Totp = { 
/**
 * Base32, for typing into the app by hand.
 */
secret: string, 
/**
 * `otpauth://totp/…`, what the QR code encodes.
 */
uri: string, 
/**
 * An SVG image of `uri`.
 */
qrSvg: string, };
