// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Stripe Checkout and customer portal; HubSpot's consent page.
 */
export type UrlResponse = { url: string, };
