// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { View } from "./View";

/**
 * `GET /api/views` — the agent's own, then those others shared, each by name.
 */
export type ViewsResponse = { views: Array<View>, };
