// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Another agent with the ticket open in the last 30 seconds (spec 006 §29).
 */
export type Viewer = { id: string, name: string, 
/**
 * Their draft on it changed in the last 60 seconds.
 */
replying: boolean, };
