// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentRef } from "./AgentRef";
import type { ViewFilters } from "./ViewFilters";

export type View = { id: string, name: string, shared: boolean, createdBy: AgentRef, filters: ViewFilters, };
