// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The same values as `GET /api/tickets`'s parameters, as JSON.
 */
export type ViewFilters = { view: 'unassigned' | 'mine' | 'open' | 'snoozed' | 'drafts' | 'closed' | 'all', q: string | null, status: Array<'new' | 'waitingOnContact' | 'waitingOnUs' | 'closed'>, 
/**
 * `me`, `none`, or agent ids.
 */
owner: Array<string>, priority: Array<'none' | 'low' | 'medium' | 'high' | 'urgent'>, 
/**
 * `none`, or category ids.
 */
category: Array<string>, created: '24h' | '7d' | '30d' | null, unread: boolean, seenBefore: boolean, sort: 'recent' | 'oldest' | 'waiting' | 'priority' | 'created', };
