// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Billing } from "./Billing";

export type Workspace = { id: string, name: string, slug: string, inboundAddress: string, language: string, billing: Billing, };
